version: '3.9'
services:
  script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wd14-tagger-01
    tty: true
    environment:
      gpus: 'all'
    volumes:
      - ./volumes/images:/images
    logging:
      options:
        max-size: '200k'
        max-file: '10'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
